[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
solc_version = "0.8.34"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"

[fmt]
line_length = 110
