import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { compile } from 'json-schema-to-typescript';
import { format } from 'prettier';

const root = resolve(import.meta.dirname, '..');
const names = ['common', 'domain', 'quote', 'api'];
const schemas = await Promise.all(
  names.map(async (name) =>
    JSON.parse(
      await readFile(resolve(root, `schemas/${name}.schema.json`), 'utf8'),
    ),
  ),
);
const definitions = {};
const refs = {};
for (let i = 0; i < names.length; i++) {
  for (const [key, value] of Object.entries(schemas[i].$defs)) {
    if (key in definitions)
      throw new Error(`Definition name collision: ${key}`);
    definitions[key] = value;
    refs[`${names[i]}.${key}`] = `${schemas[i].$id}#/$defs/${key}`;
  }
}
const localize = (value) => {
  if (Array.isArray(value)) return value.map(localize);
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, child]) => {
        if (key !== '$ref') return [key, localize(child)];
        const match =
          /^https:\/\/rwa-income-rights\.local\/schemas\/(common|domain|quote|api)\.schema\.json#\/\$defs\/(\w+)$/.exec(
            child,
          );
        if (!match || !(match[2] in definitions))
          throw new Error(`Unresolved offline reference: ${child}`);
        return [key, `#/$defs/${match[2]}`];
      }),
    );
  }
  return value;
};
const properties = Object.fromEntries(
  Object.keys(definitions).map((key) => [key, { $ref: `#/$defs/${key}` }]),
);
const header =
  '// GENERATED by pnpm generate; edit schemas or the contract spec, then regenerate.\n';
const types = await compile(
  {
    type: 'object',
    additionalProperties: false,
    properties,
    required: Object.keys(properties),
    $defs: localize(definitions),
  },
  'ProtocolWireTypes',
  {
    bannerComment: header.trim(),
    $refOptions: { resolve: { http: false } },
    enableConstEnums: false,
    unknownAny: true,
  },
);
const typeMap = `import type { ProtocolWireTypes } from './types.js';\nexport interface SchemaTypes {\n${Object.keys(
  refs,
)
  .map((key) => `  '${key}': ProtocolWireTypes['${key.split('.')[1]}'];`)
  .join('\n')}\n}\n`;
const abis = {};
for (const name of [
  'IIncomeRightsMarket',
  'ICorporateActionRegistry',
  'IAssetAdapter',
]) {
  const artifact = JSON.parse(
    await readFile(
      resolve(root, `packages/contracts/out/${name}.sol/${name}.json`),
      'utf8',
    ),
  );
  if (artifact.bytecode.object !== '0x' && artifact.bytecode.object !== '')
    throw new Error(`${name} unexpectedly has deployable bytecode`);
  abis[name] = artifact.abi;
}
const files = {
  'types.ts': types,
  'schema-types.ts': header + typeMap,
  'schemas.ts':
    header +
    `export const schemas = ${JSON.stringify(schemas)};\nexport const definitionRefs = ${JSON.stringify(refs)} as const;\n`,
  'abis.ts':
    header +
    `export const ABI_STAGE = 'INTERFACE_ONLY' as const;\nexport const interfaceAbis = ${JSON.stringify(abis)} as const;\n`,
};
const directory = resolve(root, 'packages/shared/src/generated');
const check = process.argv.includes('--check');
if (!check) await mkdir(directory, { recursive: true });
for (const [name, contents] of Object.entries(files)) {
  const output = await format(contents, {
    parser: 'typescript',
    singleQuote: true,
  });
  const path = resolve(directory, name);
  if (check) {
    if ((await readFile(path, 'utf8')) !== output)
      throw new Error(
        `Generated shared file drift: ${name}; run pnpm generate`,
      );
  } else await writeFile(path, output);
}
console.log(
  `${check ? 'Checked' : 'Generated'} ${Object.keys(refs).length} shared definitions and ${Object.keys(abis).length} interface ABIs.`,
);
